table Alcance
	lineageTag: 37edd526-1f16-417d-80de-2fb28578de91

	column Valor
		dataType: int64
		formatString: #,0
		lineageTag: 81584339-60ac-4934-ba8e-1df7fa75a723
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	column 'Data Lanc'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b5416173-bcd2-4696-aeb3-8702892d3216
		summarizeBy: none
		sourceColumn: Data Lanc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Req'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 62966d5a-4384-46f6-9c17-5c6a8ce17630
		summarizeBy: none
		sourceColumn: Data Req

		variation Variation
			isDefault
			relationship: 0c82abc9-bb3e-4e73-b95c-bce7412fb223
			defaultHierarchy: LocalDateTable_a76f567e-3b87-4883-a0be-945a87290ac6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	partition Alcance = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\NOTE RENE\Downloads\SeguidorCidade_Blackbull\Dados\Alcance.xlsx"), null, true),
				    Sheet1_Sheet = Fonte{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"value", Int64.Type}, {"end_time", type datetime}, {"Data", type datetime}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"value", "Valor"}, {"end_time", "Data Lanc"}, {"Data", "Data Req"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Data Lanc", type date}, {"Data Req", type date}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

