table LinkPerfil
	lineageTag: ca67b769-7cae-4b45-970d-82e55d022c22

	column Valor
		dataType: int64
		formatString: 0
		lineageTag: ce2621cd-848d-45eb-9789-a59026de72a4
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	column 'Data Req'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d35507cd-4215-4b3b-be31-66a23495cd0b
		summarizeBy: none
		sourceColumn: Data Req

		variation Variation
			isDefault
			relationship: 9d3454d0-42c6-4ab7-9705-791fcda0de49
			defaultHierarchy: LocalDateTable_08125041-240c-40a8-9616-f97a2e483f96.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	partition LinkPerfil = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\NOTE RENE\Downloads\SeguidorCidade_Blackbull\Dados\LinkPerfil.xlsx"), null, true),
				    Sheet1_Sheet = Fonte{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"value", Int64.Type}, {"Data", type number}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Data", "Data Req"}, {"value", "Valor"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Data Req", type datetime}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Tipo Alterado1",{{"Data Req", type date}})
				in
				    #"Tipo Alterado2"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

