table seguidores
	lineageTag: 06200fc6-2846-427e-bf94-e3156a6dbbd3

	column 'data.name'
		dataType: string
		lineageTag: 9874f540-8fce-4afa-b960-74733b2b4822
		summarizeBy: none
		sourceColumn: data.name

		annotation SummarizationSetBy = Automatic

	column 'data.period'
		dataType: string
		lineageTag: 842e1f63-c370-423f-94c8-bf6221d4e77a
		summarizeBy: none
		sourceColumn: data.period

		annotation SummarizationSetBy = Automatic

	column 'data.title'
		dataType: string
		lineageTag: 32195aa6-bc44-4835-a244-0a46c419fd64
		summarizeBy: none
		sourceColumn: data.title

		annotation SummarizationSetBy = Automatic

	column 'data.description'
		dataType: string
		lineageTag: 3da82547-30d2-4f70-b4d4-e75b958400d0
		summarizeBy: none
		sourceColumn: data.description

		annotation SummarizationSetBy = Automatic

	column 'data.total_value.breakdowns.dimension_keys'
		dataType: string
		lineageTag: 4e06ea55-e0ab-4f8a-b74e-3d52defb911c
		summarizeBy: none
		sourceColumn: data.total_value.breakdowns.dimension_keys

		annotation SummarizationSetBy = Automatic

	column 'data.total_value.breakdowns.results.dimension_values'
		dataType: string
		lineageTag: c49c4541-71d7-4be2-973e-f670bb44bb80
		summarizeBy: none
		sourceColumn: data.total_value.breakdowns.results.dimension_values

		annotation SummarizationSetBy = Automatic

	column 'data.total_value.breakdowns.results.value'
		dataType: int64
		formatString: 0
		lineageTag: 92b9a702-5ecf-4d02-a49a-594b9dfb72b5
		summarizeBy: sum
		sourceColumn: data.total_value.breakdowns.results.value

		annotation SummarizationSetBy = Automatic

	column 'data.id'
		dataType: string
		lineageTag: 0b88f8f1-3268-4eb3-bcf1-0b1746bddb91
		summarizeBy: none
		sourceColumn: data.id

		annotation SummarizationSetBy = Automatic

	partition seguidores = m
		mode: import
		source =
				let
				    Fonte = Json.Document(Web.Contents("https://graph.facebook.com/v20.0/17841468029321032/insights?metric=follower_demographics&metric_type=total_value&period=lifetime&breakdown=city&access_token=EAAKh1Nok4vQBO4z8RvOr8ZBbNsZAWUagQ9ZASxjxG7XHceZCs7z1bdyGnphFM1oA9zsM1ZAV113xIkMtoxvi46LVZATAcCes4ZBkDYZCsoVWFzzaRoIgiifuiKG6RFPZCgxF2Mh4ll9PHOZBihdDdWKAsf59pGjenlVCLy4to2YKvZCrZAlfhDNyBqZBTsBlkxoV5
				")),
				    #"Convertido para Tabela" = Table.FromRecords({Fonte}),
				    #"data Expandido" = Table.ExpandListColumn(#"Convertido para Tabela", "data"),
				    #"data Expandido1" = Table.ExpandRecordColumn(#"data Expandido", "data", {"name", "period", "title", "description", "total_value", "id"}, {"data.name", "data.period", "data.title", "data.description", "data.total_value", "data.id"}),
				    #"data.total_value Expandido" = Table.ExpandRecordColumn(#"data Expandido1", "data.total_value", {"breakdowns"}, {"data.total_value.breakdowns"}),
				    #"data.total_value.breakdowns Expandido" = Table.ExpandListColumn(#"data.total_value Expandido", "data.total_value.breakdowns"),
				    #"data.total_value.breakdowns Expandido1" = Table.ExpandRecordColumn(#"data.total_value.breakdowns Expandido", "data.total_value.breakdowns", {"dimension_keys", "results"}, {"data.total_value.breakdowns.dimension_keys", "data.total_value.breakdowns.results"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"data.total_value.breakdowns Expandido1",{{"data.name", type text}, {"data.period", type text}, {"data.title", type text}, {"data.description", type text}, {"data.total_value.breakdowns.dimension_keys", type any}, {"data.total_value.breakdowns.results", type any}, {"data.id", type text}}),
				    #"data.total_value.breakdowns.dimension_keys Expandido" = Table.ExpandListColumn(#"Tipo Alterado", "data.total_value.breakdowns.dimension_keys"),
				    #"data.total_value.breakdowns.results Expandido" = Table.ExpandListColumn(#"data.total_value.breakdowns.dimension_keys Expandido", "data.total_value.breakdowns.results"),
				    #"data.total_value.breakdowns.results Expandido1" = Table.ExpandRecordColumn(#"data.total_value.breakdowns.results Expandido", "data.total_value.breakdowns.results", {"dimension_values", "value"}, {"data.total_value.breakdowns.results.dimension_values", "data.total_value.breakdowns.results.value"}),
				    #"data.total_value.breakdowns.results.dimension_values Expandido" = Table.ExpandListColumn(#"data.total_value.breakdowns.results Expandido1", "data.total_value.breakdowns.results.dimension_values"),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"data.total_value.breakdowns.results.dimension_values Expandido",{{"data.total_value.breakdowns.results.value", Int64.Type}, {"data.total_value.breakdowns.results.dimension_values", type text}, {"data.total_value.breakdowns.dimension_keys", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

