table SeguidoresCidades
	lineageTag: ec34240a-0715-4902-ac4a-e6f25421e78b

	column Cidades
		dataType: string
		lineageTag: 2d520b5d-9105-4a12-a811-a4729d6ec94e
		summarizeBy: none
		sourceColumn: Cidades

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: int64
		formatString: #,0
		lineageTag: 52efe566-570e-4506-a338-a95317e7749e
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	column 'Data Req'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0686dcde-0663-4cb4-9a49-b1c5cc7623c4
		summarizeBy: none
		sourceColumn: Data Req

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	partition SeguidoresCidades = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\NOTE RENE\Downloads\SeguidorCidade_Blackbull\Dados\SeguidoresCidades.xlsx"), null, true),
				    Sheet1_Sheet = Fonte{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"dimension_values", type text}, {"value", Int64.Type}, {"Data", type number}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"dimension_values", "Cidades"}, {"value", "Valor"}, {"Data", "Data Req"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Data Req", type datetime}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Tipo Alterado1",{{"Data Req", type date}})
				in
				    #"Tipo Alterado2"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

